### ISSUE TITLE
native image needs freetype library starting with quarkus-tika 1.1.0

### ISSUE THREAD

**Issue by s-seidel** [quarkiverse/quarkus-tika#96]
After upgrading from 1.0.3 to 1.1.0 it seems that now libfreetype.so.6 is needed which requires to use a customized image to run the native image. Was that intentional? Is there a changelog where this is documented? Can this dependency be made optional?

**Comment by melloware** [comment]
I can submit a PR for this.  See this I added to Quarkus POI docs:

https://github.com/quarkiverse/quarkus-poi#docker
